### ISSUE TITLE
XCode 10 GM and Swift 4.2 fails to build

### ISSUE THREAD

**Issue by jlaws** [mixpanel/mixpanel-swift#234]
```
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/AutomaticEvents.swift:78:55: 'UIApplicationWillResignActive' has been renamed to 'UIApplication.willResignActiveNotification'
/Users/joelaws/Workspace/kratos/Pods/UIKit.NSNotification.Name:13:23: 'UIApplicationWillResignActive' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/AutomaticEvents.swift:83:55: 'UIApplicationDidBecomeActive' has been renamed to 'UIApplication.didBecomeActiveNotification'
/Users/joelaws/Workspace/kratos/Pods/UIKit.NSNotification.Name:11:23: 'UIApplicationDidBecomeActive' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/TakeoverNotificationViewController.swift:41:31: 'UIInterfaceOrientationIsLandscape' has been replaced by property 'UIInterfaceOrientation.isLandscape'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIInterfaceOrientationIsLandscape:2:13: 'UIInterfaceOrientationIsLandscape' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/TakeoverNotificationViewController.swift:61:41: 'UIViewContentMode' has been renamed to 'UIView.ContentMode'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIViewContentMode:2:18: 'UIViewContentMode' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/TakeoverNotificationViewController.swift:69:43: 'NSLayoutAttribute' has been renamed to 'NSLayoutConstraint.Attribute'
/Users/joelaws/Workspace/kratos/Pods/UIKit.NSLayoutAttribute:2:18: 'NSLayoutAttribute' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/TakeoverNotificationViewController.swift:76:43: 'NSLayoutAttribute' has been renamed to 'NSLayoutConstraint.Attribute'
/Users/joelaws/Workspace/kratos/Pods/UIKit.NSLayoutAttribute:2:18: 'NSLayoutAttribute' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/TakeoverNotificationViewController.swift:92:48: 'UIControlState' has been renamed to 'UIControl.State'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlState:2:18: 'UIControlState' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/TakeoverNotificationViewController.swift:96:46: 'UIViewContentMode' has been renamed to 'UIView.ContentMode'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIViewContentMode:2:18: 'UIViewContentMode' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/TakeoverNotificationViewController.swift:104:47: 'NSLayoutAttribute' has been renamed to 'NSLayoutConstraint.Attribute'
/Users/joelaws/Workspace/kratos/Pods/UIKit.NSLayoutAttribute:2:18: 'NSLayoutAttribute' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/TakeoverNotificationViewController.swift:130:52: 'UIControlState' has been renamed to 'UIControl.State'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlState:2:18: 'UIControlState' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/TakeoverNotificationViewController.swift:134:78: 'UIControlState' has been renamed to 'UIControl.State'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlState:2:18: 'UIControlState' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/TakeoverNotificationViewController.swift:135:78: 'UIControlState' has been renamed to 'UIControl.State'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlState:2:18: 'UIControlState' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/TakeoverNotificationViewController.swift:136:78: 'UIControlState' has been renamed to 'UIControl.State'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlState:2:18: 'UIControlState' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/TakeoverNotificationViewController.swift:139:78: 'UIControlEvents' has been renamed to 'UIControl.Event'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlEvents:2:18: 'UIControlEvents' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/TakeoverNotificationViewController.swift:150:34: 'UIWindowLevelAlert' has been renamed to 'UIWindow.Level.alert'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIWindowLevelAlert:2:12: 'UIWindowLevelAlert' was obsoleted in Swift 3
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/UIControlBinding.swift:14:23: 'UIControlEvents' has been renamed to 'UIControl.Event'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlEvents:2:18: 'UIControlEvents' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/UIControlBinding.swift:15:22: 'UIControlEvents' has been renamed to 'UIControl.Event'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlEvents:2:18: 'UIControlEvents' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/UIControlBinding.swift:19:57: 'UIControlEvents' has been renamed to 'UIControl.Event'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlEvents:2:18: 'UIControlEvents' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/UIControlBinding.swift:39:83: 'UIControlEvents' has been renamed to 'UIControl.Event'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlEvents:2:18: 'UIControlEvents' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/UIControlBinding.swift:44:31: 'UIControlEvents' has been renamed to 'UIControl.Event'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlEvents:2:18: 'UIControlEvents' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/UIControlBinding.swift:45:78: 'UIControlEvents' has been renamed to 'UIControl.Event'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlEvents:2:18: 'UIControlEvents' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/UIControlBinding.swift:47:34: 'UIControlEvents' has been renamed to 'UIControl.Event'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlEvents:2:18: 'UIControlEvents' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/UIControlBinding.swift:49:34: 'UIControlEvents' has been renamed to 'UIControl.Event'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlEvents:2:18: 'UIControlEvents' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/UIControlBinding.swift:58:33: 'UIControlEvents' has been renamed to 'UIControl.Event'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlEvents:2:18: 'UIControlEvents' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/UIControlBinding.swift:64:24: 'UIControlEvents' has been renamed to 'UIControl.Event'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlEvents:2:18: 'UIControlEvents' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/UIControlBinding.swift:65:23: 'UIControlEvents' has been renamed to 'UIControl.Event'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlEvents:2:18: 'UIControlEvents' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/UIControlBinding.swift:129:52: 'UIControlEvents' has been renamed to 'UIControl.Event'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlEvents:2:18: 'UIControlEvents' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/UIControlBinding.swift:176:27: 'UIControlEvents' has been renamed to 'UIControl.Event'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlEvents:2:18: 'UIControlEvents' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/UIControlBinding.swift:199:27: 'UIControlEvents' has been renamed to 'UIControl.Event'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlEvents:2:18: 'UIControlEvents' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/UIImageToNSDictionary.swift:48:32: 'UIImagePNGRepresentation' has been replaced by instance method 'UIImage.pngData()'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIImagePNGRepresentation:2:13: 'UIImagePNGRepresentation' was obsoleted in Swift 3
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/UIImageToNSDictionary.swift:126:79: 'UIImageResizingMode' has been renamed to 'UIImage.ResizingMode'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIImageResizingMode:2:18: 'UIImageResizingMode' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/SnapshotMessage.swift:101:48: 'UIImageJPEGRepresentation' has been replaced by instance method 'UIImage.jpegData(compressionQuality:)'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIImageJPEGRepresentation:2:13: 'UIImageJPEGRepresentation' was obsoleted in Swift 3
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MiniNotificationViewController.swift:55:12: 'UIInterfaceOrientationIsPortrait' has been replaced by property 'UIInterfaceOrientation.isPortrait'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIInterfaceOrientationIsPortrait:2:13: 'UIInterfaceOrientationIsPortrait' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MiniNotificationViewController.swift:69:34: 'UIWindowLevelAlert' has been renamed to 'UIWindow.Level.alert'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIWindowLevelAlert:2:12: 'UIWindowLevelAlert' was obsoleted in Swift 3
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MiniNotificationViewController.swift:104:46: 'UIGestureRecognizerState' has been renamed to 'UIGestureRecognizer.State'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIGestureRecognizerState:2:18: 'UIGestureRecognizerState' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MiniNotificationViewController.swift:115:18: 'UIGestureRecognizerState' has been renamed to 'UIGestureRecognizer.State'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIGestureRecognizerState:2:18: 'UIGestureRecognizerState' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MiniNotificationViewController.swift:117:18: 'UIGestureRecognizerState' has been renamed to 'UIGestureRecognizer.State'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIGestureRecognizerState:2:18: 'UIGestureRecognizerState' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MiniNotificationViewController.swift:122:18: 'UIGestureRecognizerState' has been renamed to 'UIGestureRecognizer.State'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIGestureRecognizerState:2:18: 'UIGestureRecognizerState' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MiniNotificationViewController.swift:146:16: 'UIInterfaceOrientationIsPortrait' has been replaced by property 'UIInterfaceOrientation.isPortrait'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIInterfaceOrientationIsPortrait:2:13: 'UIInterfaceOrientationIsPortrait' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/Mixpanel.swift:40:48: 'UIApplicationLaunchOptionsKey' has been renamed to 'UIApplication.LaunchOptionsKey'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIApplicationLaunchOptionsKey:2:18: 'UIApplicationLaunchOptionsKey' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/Mixpanel.swift:144:37: 'UIApplicationLaunchOptionsKey' has been renamed to 'UIApplication.LaunchOptionsKey'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIApplicationLaunchOptionsKey:2:18: 'UIApplicationLaunchOptionsKey' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MixpanelInstance.swift:245:18: 'UIBackgroundTaskInvalid' has been renamed to 'UIBackgroundTaskIdentifier.invalid'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIBackgroundTaskInvalid:3:12: 'UIBackgroundTaskInvalid' was obsoleted in Swift 3
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MixpanelInstance.swift:257:45: 'UIApplicationLaunchOptionsKey' has been renamed to 'UIApplication.LaunchOptionsKey'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIApplicationLaunchOptionsKey:2:18: 'UIApplicationLaunchOptionsKey' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MixpanelInstance.swift:375:51: 'UIApplicationWillTerminate' has been renamed to 'UIApplication.willTerminateNotification'
/Users/joelaws/Workspace/kratos/Pods/UIKit.NSNotification.Name:17:23: 'UIApplicationWillTerminate' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MixpanelInstance.swift:379:51: 'UIApplicationWillResignActive' has been renamed to 'UIApplication.willResignActiveNotification'
/Users/joelaws/Workspace/kratos/Pods/UIKit.NSNotification.Name:13:23: 'UIApplicationWillResignActive' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MixpanelInstance.swift:383:51: 'UIApplicationDidBecomeActive' has been renamed to 'UIApplication.didBecomeActiveNotification'
/Users/joelaws/Workspace/kratos/Pods/UIKit.NSNotification.Name:11:23: 'UIApplicationDidBecomeActive' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MixpanelInstance.swift:387:51: 'UIApplicationDidEnterBackground' has been renamed to 'UIApplication.didEnterBackgroundNotification'
/Users/joelaws/Workspace/kratos/Pods/UIKit.NSNotification.Name:4:23: 'UIApplicationDidEnterBackground' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MixpanelInstance.swift:391:51: 'UIApplicationWillEnterForeground' has been renamed to 'UIApplication.willEnterForegroundNotification'
/Users/joelaws/Workspace/kratos/Pods/UIKit.NSNotification.Name:7:23: 'UIApplicationWillEnterForeground' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MixpanelInstance.swift:511:27: 'UIBackgroundTaskInvalid' has been renamed to 'UIBackgroundTaskIdentifier.invalid'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIBackgroundTaskInvalid:3:12: 'UIBackgroundTaskInvalid' was obsoleted in Swift 3
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MixpanelInstance.swift:525:31: 'UIBackgroundTaskInvalid' has been renamed to 'UIBackgroundTaskIdentifier.invalid'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIBackgroundTaskInvalid:3:12: 'UIBackgroundTaskInvalid' was obsoleted in Swift 3
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MixpanelInstance.swift:527:31: 'UIBackgroundTaskInvalid' has been renamed to 'UIBackgroundTaskIdentifier.invalid'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIBackgroundTaskInvalid:3:12: 'UIBackgroundTaskInvalid' was obsoleted in Swift 3
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MixpanelInstance.swift:538:31: 'UIBackgroundTaskInvalid' has been renamed to 'UIBackgroundTaskIdentifier.invalid'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIBackgroundTaskInvalid:3:12: 'UIBackgroundTaskInvalid' was obsoleted in Swift 3
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MixpanelInstance.swift:540:31: 'UIBackgroundTaskInvalid' has been renamed to 'UIBackgroundTaskIdentifier.invalid'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIBackgroundTaskInvalid:3:12: 'UIBackgroundTaskInvalid' was obsoleted in Swift 3
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/MixpanelInstance.swift:668:29: 'UIGestureRecognizerState' has been renamed to 'UIGestureRecognizer.State'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIGestureRecognizerState:2:18: 'UIGestureRecognizerState' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/ObjectFilter.swift:180:41: 'childViewControllers' has been renamed to 'children'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIViewController:6:14: 'childViewControllers' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/UIViewSelectors.swift:86:47: 'UIControlState' has been renamed to 'UIControl.State'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlState:2:18: 'UIControlState' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/UIViewSelectors.swift:127:32: 'UIControlEvents' has been renamed to 'UIControl.Event'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlEvents:2:18: 'UIControlEvents' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/UIViewSelectors.swift:132:40: 'UIControlEvents' has been renamed to 'UIControl.Event'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlEvents:2:18: 'UIControlEvents' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/VariantAction.swift:288:80: 'UIControlState' has been renamed to 'UIControl.State'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlState:2:18: 'UIControlState' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/VariantAction.swift:292:71: 'UIControlState' has been renamed to 'UIControl.State'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlState:2:18: 'UIControlState' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/VariantAction.swift:321:80: 'UIControlState' has been renamed to 'UIControl.State'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlState:2:18: 'UIControlState' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/VariantAction.swift:329:81: 'UIControlState' has been renamed to 'UIControl.State'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIControlState:2:18: 'UIControlState' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/WebSocketWrapper.swift:176:57: 'UIWindowLevelAlert' has been renamed to 'UIWindow.Level.alert'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIWindowLevelAlert:2:12: 'UIWindowLevelAlert' was obsoleted in Swift 3
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/WebSocketWrapper.swift:186:43: 'bringSubview(toFront:)' has been renamed to 'bringSubviewToFront(_:)'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIView:17:15: 'bringSubview(toFront:)' was obsoleted in Swift 4.2
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/WebSocketWrapper.swift:215:66: 'kCAMediaTimingFunctionEaseOut' has been renamed to 'CAMediaTimingFunctionName.easeOut'
/Users/joelaws/Workspace/kratos/Pods/QuartzCore.kCAMediaTimingFunctionEaseOut:3:12: 'kCAMediaTimingFunctionEaseOut' was obsoleted in Swift 3
/Users/joelaws/Workspace/kratos/Pods/Mixpanel-swift/Mixpanel/WebSocketWrapper.swift:216:32: 'kCAFillModeForwards' has been renamed to 'CAMediaTimingFillMode.forwards'
/Users/joelaws/Workspace/kratos/Pods/QuartzCore.kCAFillModeForwards:3:12: 'kCAFillModeForwards' was obsoleted in Swift 3
```

**Comment by zihejia** [comment]
hi @jlaws Our sdk does not support Swift 4.2 just yet. If possible, could you switch to Swift 4.1 for Mixpanel as a workaround just for now?

**Comment by zihejia** [comment]
@jlaws for sure, we will do it as a high priority.

**Comment by yusuftor** [comment]
Please could you merge the swift 4.2 branch?

**Comment by piers12** [comment]
Any update on when this will be fixed?

**Comment by kuzdu** [comment]
Same here. Hoping for an update very soon

**Comment by zihejia** [comment]
We have released 2.5.0 which supports Xcode 10 and swift 4.2.

**Comment by angelolloqui** [comment]
I am trying to install the `2.5.0` version with cocoapods and I am still getting errors.  For example:

`UIApplication.willResignActiveNotification` is now `NSNotification.Name.UIApplicationWillResignActive`.

Can you please prioritize SDK support for Xcode 10 ASAP?

**Comment by zihejia** [comment]
For anyone who has upgraded from previous version, if having any error, please set swift 4.2 to `Mixpanel` target.

**Comment by jlaws** [comment]
Works great, thank you!
