### ISSUE TITLE
Crash when deploying to WatchOS 5 from Xcode 11

### ISSUE THREAD

**Issue by tealshift** [mixpanel/mixpanel-swift#329]
**Integration Method:** CocoaPods
**Xcode Version:** 11 GM Seed 2
**Library Version:** 2.6.5 (edit: fixed)
**Platform:** watchOS 5.3.1
**Language:** Swift & Objective-C
**Description:** I get this https://stackoverflow.com/questions/57979776/dyld-abort-with-payload-crash-from-xcode-11-on-watchos-5?noredirect=1#comment102375400_57979776 crash on launch. Removing the pod resolves the mysterious crash.
I don't know if it matters, but the parent iOS app also contains the 'Mixpanel-swift' pod.
**Expected Behavior:** App should launch normally

**Comment by zihejia** [comment]
Hi @tealshift , i couldn't reproduce the issue. Do you still have this issue? If not, have you tried a clean build?

**Comment by zihejia** [comment]
hi @tealshift, any update? We also released v2.6.6 which complied with Xcode11, you can have a try. https://github.com/mixpanel/mixpanel-swift/releases/tag/v2.6.6

**Comment by tealshift** [comment]
Yes, I've updated to 2.6.6 but the issue remains. I ran my watch app with "pod mixpanel-swift" and (pod install), got the crash, removed it and did another pod install, and it launches without crash. :(

**Comment by zihejia** [comment]
hi @tealshift , could you share the crash log?

**Comment by tealshift** [comment]
Unfortunately I can't seem to find any crash log file from the simulator (I don't have a physical device with me to produce one), but Xcode spits this out:

> dyld: lazy symbol binding failed: Symbol not found: _WKExtensionMain
>   Referenced from: /~/Library/Developer/CoreSimulator/Devices/3E160163-5C05-4651-912F-0B6CDD523E12/data/Containers/Bundle/Application/16D79027-BFF0-46E2-A0D9-1C06D680138B/Watch.app/PlugIns/Watch Extension.appex/Watch Extension
>   Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/watchOS 5.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/WatchKit.framework/WatchKit
> 
> dyld: Symbol not found: _WKExtensionMain
>   Referenced from: /~/Library/Developer/CoreSimulator/Devices/3E160163-5C05-4651-912F-0B6CDD523E12/data/Containers/Bundle/Application/16D79027-BFF0-46E2-A0D9-1C06D680138B/Watch.app/PlugIns/Watch Extension.appex/Watch Extension
>   Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/watchOS 5.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/WatchKit.framework/WatchKit

**Comment by cvlehe** [comment]
Having the same issue installing to a physical Apple Watch.

**Comment by zihejia** [comment]
Thanks @tealshift @cvlehe for bringing this up, will take a look.

**Comment by zihejia** [comment]
Hi @tealshift @cvlehe , the issue has been fixed in v2.6.7. Please feel free to reopen it if the problem still exists.
https://github.com/mixpanel/mixpanel-swift/releases/tag/v2.6.7

**Comment by cvlehe** [comment]
All good now. Thanks!
