### ISSUE TITLE
SPM support for watchOS?

### ISSUE THREAD

**Issue by jasonzurita** [mixpanel/mixpanel-swift#415]
Is there any plan to support watchOS when using Swift Package Manager? The `Package.swift` file includes watchOS as a supported platform, but based on the below quote from the README and me trying to install it via SPM anyway for watchOS (many errors) looks like it isn't supported.

> Important: we only have support for iOS, for now, if you need integrations for other platforms(tvOS or macOS), please use other integration methods instead

**Comment by jasonzurita** [comment]
Just want to check in to see if there was any update on this?

**Comment by zihejia** [comment]
Hi @jasonzurita , it's in our backlog. We will let you know when we start working on it. Thanks for raising it.

**Comment by jasonzurita** [comment]
Thanks, I look forward to it!

**Comment by zihejia** [comment]
hi @jasonzurita , we will release a version by April that does not have Messages and Experiments support but it will support SPM for watchOS and macOS. If you don't use Mixpanel for push notification and a/b testing, you can opt into that version.

**Comment by tealshift** [comment]
Bump? @zihejia

**Comment by bmalbuck** [comment]
Any updates to support watchOS SPM?

**Comment by zihejia** [comment]
Hello everyone! Sorry for the waiting. We've now added SPM support to our [3.0.0.beta](https://github.com/mixpanel/mixpanel-swift/releases/tag/v3.0.0.beta.2) release for watchOS. 
```
1.  In Xcode, select File > Swift Packages > Add Package Dependency.
2.  Follow the prompts using the URL for this repository and point to the branch `3.0.0.beta`
```
Here is more context:
On Jan 1, 2022, we’ll remove the [Messages & Experiments(M&E)](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/#:~:text=A%20year%20from%20now%2C%20on,offering%20discounts%20for%20getting%20started) feature from Mixpanel. If you are not using messages or A/B testing, you can definitely use this beta version and it's in 100% parity with the main version excluding the M&E feature.

Going forward, we don't have a plan to add watchOS SPM support to the 2.x.x release. It will only be available to 3.0.0+.  I'm closing this issue now, please feel free to reopen if there are issues on the 3.0.0.beta branch for the watchOS SPM support

**Comment by tealshift** [comment]
Hi, thanks for the update! I have installed the SPM lib on branch `3.0.0.beta` and get missing dependency errors. One of which is the type `SSLSecurity` which would be in SSLSecurity.swift but that file is not present under the Sources directory. 
I hope I'm not just missing something obvious. Hope this helps!

**Comment by zihejia** [comment]
hi @tealshift , `SSLSecurity` no longer exists, have you tried cleaning all your build cache and the SPM cache?

**Comment by tealshift** [comment]
@zihejia  Yes, I believe I have (though I'm not sure about the SPM cache clearing procedure)... but I see this file here https://github.com/mixpanel/mixpanel-swift/blob/3.0.0.beta/Sources/WebSocket.swift still references `SSLSecurity` so I don't understand how that could be.

**Comment by zihejia** [comment]
hi @tealshift , sorry the file shouldn't be there. I just fixed that. Would you like to try again?

**Comment by tealshift** [comment]
Brilliant! No build errors remain. Thank you @zihejia :) 
I'm so happy I don't need cocoapods anymore XD

**Comment by jasonzurita** [comment]
Works great, thanks so much for this!!
