### ISSUE TITLE
exec_bad_access in mp_controllerVariable in UIViewSelectors.swift

### ISSUE THREAD

**Issue by gugaoliveira** [mixpanel/mixpanel-swift#51]
I am getting exec_bad_access in UIViewSelectors.swift in this method

```
 func mp_controllerVariable() -> String? {
        if self is UIControl {
            var responder = self.next
            while responder != nil && !(responder is UIViewController) {
                responder = responder?.next
            }
            if let responder = responder {
                let mirrored_object = Mirror(reflecting: responder)

                for (_, attr) in mirrored_object.children.enumerated() {   ****  exec_bad_access


                    if let property_name = attr.label {
                        if let value = attr.value as? UIView, value == self {
                            return property_name
                        }
                    }
                }
            }
        }
```

<img width="1733" alt="mixpanel_error" src="https://cloud.githubusercontent.com/assets/3792492/21249975/ef5ebb36-c328-11e6-8d72-7aae78ff4e69.png">

**Comment by yarneo** [comment]
Hey @gugaoliveira! Seems like this could be an apple issue. Could you tell me what configuration (what iPhone/Simulator) you are using, what's the version and build (iOS version), and how often it reproduces? Also, if it is easily reproducible could you do a "po self", "po responder" and "po mirrored_object" in the console and show me what it prints? 

That information will help us understand more about why this is happening and open a rdar if needed. thanks!

**Comment by yarneo** [comment]
closing as this isn't reproducible on our end and seems to be an apple bug. feel free to re-open this issue if you find more information regarding the crash. thanks for the report!

**Comment by marcosgriselli** [comment]
Can we reopen it? I'm having the same issue on 
**Swift version** : 3.0
**pod version** :  2.1.4
**Xcode version** : 8.2.1
**iPhone hardware** : 6s
**iOS version** : 10.2.1

Strangely is not happening on the simulator and it doesn't happen on the **first** run (after uninstalling) on the real device, but it's crashing 100% of the time in consequent runs. 

<img width="1552" alt="screen shot 2017-03-21 at 10 18 57 pm" src="https://cloud.githubusercontent.com/assets/14804033/24178226/9811895e-0e86-11e7-82d3-e7958032f1bb.png">

**Comment by yarneo** [comment]
You are awesome, thank you! I'm reopening this so we can investigate it further. I'll let you know if we need more information. If however you are able to provide a sample project where this is reproducible that would be the easiest. Thanks!

**Comment by marcosgriselli** [comment]
@yarneo Thanks for the quick reply. I added an edit to the previous comment. I'll try to reproduce it on a sample project. Any wild guess on what I should look for? Cause I have no idea what can be causing it.

**Comment by marcosgriselli** [comment]
@yarneo any update or recommendations? We need to push a new version to the App Store and this issue is holding us. If this has anything to do with Autotracking we can turn it off for now.

**Comment by yarneo** [comment]
Hey @marcosgriselli , sorry for the late reply!
Honestly if I had to guess the reason for this crash it is because there is some kind of object type, or hierarchy of elements that we never tested and therefore didn't handle properly. It is hard to say exactly what, but what I'm going to be doing from my end, is trying different sample apps and seeing if I can reproduce the crash. 
Another guess, is that it could be that there is some deallocation of memory specifically in certain apps and we are trying to access that memory but aren't retaining properly.

In terms of a quick fix, then yes, that chunk of code is related to the A/B testing and auto tracking, so if you remove those from the app, you should be fine!

**Comment by marcosgriselli** [comment]
@yarneo thanks! I'll try removing it from the app for now. Haven't had the time to setup a demo project but the current viewController that causes the crash on presenting has:

1.  `AVPlayerLayer`
2. `CAGradientLayer`
3. Many `UIView`s
4. ChildViewController's view 
5. Many `NSLayoutConstraint` as `IBOutlet`

I'll try to replicate the UI over the weekend if I have some time, ping me if I can add any more information that would be useful for you.

**Comment by yarneo** [comment]
Hey @marcosgriselli we believe this issue should be resolved in the new release. If you have a chance please check it out whenever convenient and let us know :)

**Comment by marcosgriselli** [comment]
@yarneo still happening, anyway the project that had the issue is no longer being developed. I'm sure it was due to some excesive view/layers handling on our side.

**Comment by ridea-co** [comment]
In our case, it is an initialized Timer (Controller is triggered by performSegue, not too sure if it is relevant) that caused the crash.
e.g.
class SomeViewController: UIViewController {
  var timer = Timer()
}

See if helps to reproduce the issue

**Comment by hirorir** [comment]
Receiving the same issue, occurs on any UIView.addSubview(...) call within the viewDidLoad function of a particular UIViewController.

**Comment by zihejia** [comment]
closing this one now, any one facing the same issue could try @hirorir 's fix, otherwise please reopen it anytime.
