### ISSUE TITLE
Swiftlint not allowing me to build using Carthage

### ISSUE THREAD

**Issue by JagCesar** [mixpanel/mixpanel-swift#57]
Hey guys!

I'm trying to compile your repo using carthage with the command `carthage bootstrap --platform iOS --no-use-binaries --use-ssh`.

However Swiftlint tells me the code has errors (breaking coding conventions ofc, so nothing serious :P) and it fails to compile. So the only way for me to build this repo using Carthage is to uninstall Swiftlint before bootstrapping.

Is this something you are aware about?

**Comment by nerd0geek1** [comment]
Same problem.
So I can't install mixpanel-swift via Carthage on Circle CI.

**Comment by JagCesar** [comment]
@nerd0geek1 Great! I was worried I was doing something wrong :P

I see two solutions:
- Remove the swiftlint run script phase
or
- Make sure to always be up to date with the latest swiftlint version and update the code accordingly.

Option 1 makes more sense since it doesn't work to be forced to push a new release only because Swiftlint has released a new update with new rules.

**Comment by nerd0geek1** [comment]
@JagCesar 
I think so.
Or solve this problem in this way.
https://github.com/mixpanel/mixpanel-swift/issues/24#issuecomment-260787577

**Comment by yarneo** [comment]
Thanks for letting us know about the swiftlint update creating new warnings. I have pushed out a commit removing swiftlint entirely from our build phase. We definitely should not be dependent on their updates not breaking things. Hopefully this solves your problem!

**Comment by stevethomp** [comment]
I'm still seeing this issue when I run `carthage update mixpanel-swift --platform iOS --no-use-binaries --use-ssh`. 

I tried adding mix panel to my Cartfile as `github "mixpanel/mixpanel-swift" "HEAD"` to make sure I get the most recent commit.

Error is:
> *** Checking out mixpanel-swift at "55a54ecdabf31611d21ccab750e6ca22f1dbe54b"
*** xcodebuild output can be found in /var/folders/31/m7gckj7x7y1cgx9dw97lbj3cc6hxxk/T/carthage-xcodebuild.eWRFUy.log
*** Building scheme "Mixpanel" in MixpanelDemo.xcworkspace
** BUILD FAILED **
...
Carthage/Checkouts/mixpanel-swift/Mixpanel/BaseNotificationViewController.swift:24:14: error: Type Name Violation: Type name should start with an uppercase character: 'dark' (type_name)
...
PhaseScriptExecution Run\ Script /Users/.../Library/Developer/Xcode/DerivedData/MixpanelDemo-dgutzomixmfksrgopdclmhiwqdxx/Build/Intermediates/Mixpanel.build/Release-iphoneos/Mixpanel.build/Script-E1345A791D46C9A200496D0D.sh

**Comment by yarneo** [comment]
@stevethomp let me know if you are still witnessing this on master, if you are, i will take a look this week to try and resolve this. Thanks!

**Comment by stevethomp** [comment]
Sorry @yarneo for the delay, I am still getting the same error. I'm only seeing "Type name should start with an uppercase character:" errors, but just a lot of them.

**Comment by yarneo** [comment]
you're welcome, glad it works! 👍

**Comment by nerd0geek1** [comment]
@yarneo 
By the way, for this problem, how about adding Aggregate target to run SwiftLint only on development?
If it is okay, I'll send pr for that.
